resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: SAST-pr
  type: pull-request
  source:
    repo: {{repo}}
    access_token: {{git-repo-token}}

- name: git-repo
  type: git
  source:
    uri: {{git-repo}}
    username: {{git-username}}
    password: {{git-password}}

- name: sast-image
  type: docker-image
  source:
    repository: tgbenson/jssast
    tag: latest


jobs:
- name: predeploy-SAST-test
  plan:
  - get: git-repo
    trigger: true
  - get: sast-image
  - task: unit
    file: git-repo/predeploy-sast.yml
    image: sast-image
    params:
      GIT_REPO_TOKEN: {{git-repo-token}}
      SONAR_TOKEN: {{sonar-token}}
      SONAR_JAVA_BINARIES: {{sonar-java-binaries}}
      SONAR_SOURCES: {{sonar-sources}}
      SONAR_PROJECT_VERSION: {{sonar-project-version}}
      SONAR_PROJECT_NAME: {{sonar-project-name}}
      SONAR_PROJECT_KEY: {{sonar-project-key}}
      SONAR_URL: {{sonar-url}}
- name: pr-SAST-test
  plan:
  - get: SAST-pr
    trigger: true
  - get: git-repo
  - get: sast-image
  - put: SAST-pr
    params:
      path: SAST-pr
      status: pending
  - task: unit
    config:
      image_resource:
        type: docker-image
        source:
          repository: tgbenson/jssast
      inputs:
      - name: SAST-pr
      platform: linux
      run:
        path: sh
        args: ['-c', 'cd SAST-pr;retire --path . --outputformat text --outputpath retire.txt;eslint -c /opt/configs/static/.eslintrc --debug . -o ./eslint.txt;./mvnw clean install findbugs:findbugs;cat *.txt;sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.projectName=$SONAR_PROJECT_NAME -Dsonar.projectVersion=$SONAR_PROJECT_VERSION -Dsonar.sources=$SONAR_SOURCES -Dsonar.java.binaries=$SONAR_JAVA_BINARIES -Dsonar.analysis.mode=preview -Dsonar.github.pullRequest=$(git config --get pullrequest.id) -Dsonar.github.repository=$REPO -Dsonar.github.oauth=$GIT_REPO_TOKEN -Dsonar.login=$SONAR_TOKEN']
    params:
      GIT_REPO_TOKEN: {{git-repo-token}}
      SONAR_TOKEN: {{sonar-token}}
      SONAR_JAVA_BINARIES: {{sonar-java-binaries}}
      SONAR_SOURCES: {{sonar-sources}}
      SONAR_PROJECT_VERSION: {{sonar-project-version}}
      SONAR_PROJECT_NAME: {{sonar-project-name}}
      SONAR_PROJECT_KEY: {{sonar-project-key}}
      SONAR_URL: {{sonar-url}}
    on_success:
      put: SAST-pr
      params:
        path: SAST-pr
        status: success
    on_failure:
      put: SAST-pr
      params:
        path: SAST-pr
        status: failure
