resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: SAST-pr
  type: pull-request
  source:
    repo: {{repo}}
    access_token: {{repo-token}}

- name: git-repo
  type: git
  source:
    uri: {{git-repo}}
    username: {{git-username}}
    password: {{git-password}}

- name: sast-image
  type: docker-image
  source:
    repository: tgbenson/jssast
    tag: latest


jobs:
- name: predeploy-SAST-test
  plan:
  - get: git-repo
    trigger: true
  - get: sast-image
  - task: unit
    file: git-repo/predeploy-sast.yml
    image: sast-image

- name: pr-SAST-test
  plan:
  - get: SAST-pr
    trigger: true
  - get: sast-image
  - put: SAST-pr
    params:
      path: SAST-pr
      status: pending
  - task: unit
    file: SAST-pr/pr-sast.yml
    image: sast-image
    on_success:
      put: SAST-pr
      params:
        path: SAST-pr
        status: success
    on_failure:
      put: SAST-pr
      params:
        path: SAST-pr
        status: failure
