resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/ToddBenson/concourse-maven-spring-boot.git
      branch: master

  - name: deploy-cf-dev
    type: cf
    source:
      api: api.run.pivotal.io
      username: todd.benson@csaa.com
      password: {{cf-da-password}}
      organization: todd.benson
      space: development
      skip_cert_check: true

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/concourse/tasks/package.yml
    - put: deploy-cf-dev
      params:
        manifest: source-code/concourse/tasks/dev-manifest.yml
        path: release/*.war