platform: linux

image_resource:
  type: docker-image
  source:
    repository: sonarqube
    tag: latest

inputs:
  - name: source-code

run:
  path: source-code
  args:
  - -exc
  - |
  mvnw -f source-code/pom.xml package sonar:sonar
  cp ./target/*.war ../release

outputs:
  - name: release

params:
  MAVEN_BASEDIR: source-code
